<a href="https://colab.research.google.com/github/GarimaChaubey/NLP-Natural-Language-Preprocessing-/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Word Embedding Techniques using Embedding Layer in Keras

In [1]:
!pip install --upgrade pip setuptools wheel


In [3]:
pip install tensorflow


In [5]:
pip install tensorflow-gpu==2.10.0


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 578.0/578.0 MB 34.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 70.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 51.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 103.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 116.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 37.7 MB/s eta 0:00:00
  Attempting uninstall: keras
    Found existing installation: keras 3.4.1
    Uninstalling keras-3.4.1:
      Successfully uninstalled keras-3.4.1
  Attempting uninstall: tensorboard-data-server
    Found existing installation: tensorboard-data-server 0.7.2
    Uninstalling tensorboard-data-server-0.7.2:
      Successfully uninstalled tensorboard-data-server-0.7.2
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
sent= [ 'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
#Vocabulary size

voc_size=10000

# One Hot Representation

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4796, 1312, 74, 18], [4796, 1312, 74, 7130], [4796, 5749, 74, 8148], [9118, 2815, 3990, 1020, 5860], [9118, 2815, 3990, 1020, 4990], [2702, 4796, 7738, 74, 4534], [2774, 9489, 3235, 1020]]


# Word Embedding Representation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [13]:
#pre padding
sent_length=8
Embedded_docs=pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(Embedded_docs)

[[   0    0    0    0 4796 1312   74   18]
 [   0    0    0    0 4796 1312   74 7130]
 [   0    0    0    0 4796 5749   74 8148]
 [   0    0    0 9118 2815 3990 1020 5860]
 [   0    0    0 9118 2815 3990 1020 4990]
 [   0    0    0 2702 4796 7738   74 4534]
 [   0    0    0    0 2774 9489 3235 1020]]


In [15]:
dim=10

In [16]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')


In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.predict(Embedded_docs[0])

1/1 [==============================] - 0s 33ms/step


array([[ 0.01483876,  0.00433633, -0.0346715 ,  0.02936799, -0.03359811,
        -0.02531052, -0.04031903,  0.02573582, -0.00102029, -0.04290589],
       [ 0.01483876,  0.00433633, -0.0346715 ,  0.02936799, -0.03359811,
        -0.02531052, -0.04031903,  0.02573582, -0.00102029, -0.04290589],
       [ 0.01483876,  0.00433633, -0.0346715 ,  0.02936799, -0.03359811,
        -0.02531052, -0.04031903,  0.02573582, -0.00102029, -0.04290589],
       [ 0.01483876,  0.00433633, -0.0346715 ,  0.02936799, -0.03359811,
        -0.02531052, -0.04031903,  0.02573582, -0.00102029, -0.04290589],
       [ 0.03147623,  0.0227784 ,  0.0008427 , -0.03950626,  0.03184758,
         0.02821219, -0.02468854, -0.0278953 ,  0.00228953,  0.02531071],
       [ 0.03943745,  0.00949579, -0.03524401,  0.03523133,  0.03680165,
        -0.00338542,  0.01311393,  0.04637489,  0.00012372,  0.02171726],
       [-0.0009197 ,  0.00192577,  0.01010276,  0.03981947, -0.02739859,
        -0.0374194 , -0.0361702 ,  0.01257149